### ISSUE TITLE
Git.exe missing in Release job

### ISSUE THREAD

**Issue by GrumpyMeow** [dtzar/vsts-gitmerge#13]
Hi,

I've just tried to use this extension in our Hosted VSTS environment. When i use this task it will fail because it can't find git.exe. I've also tried to set the release variable "system.prefergit", but that does not seem to work also.
Any ideas?

**Comment by dtzar** [comment]
I've run this in release on the VS Hosted, VS 2017 Hosted, and Ubuntu 1604 Hosted pools and I cannot reproduce this error.  I'm guessing it is resolved now via transient issues or via my latest updates.  If you are still seeing this problem please reply to this issue with more details so I can reproduce.
